--liquibase formatted sql

--changeset slothub:001-create-venues
CREATE TABLE venues
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255)             NOT NULL,
    city       VARCHAR(100)             NOT NULL,
    address    VARCHAR(500)             NOT NULL,
    timezone   VARCHAR(64)              NOT NULL,
    opens_at   TIME                     NOT NULL,
    closes_at  TIME                     NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
--rollback DROP TABLE venues;
