--liquibase formatted sql

--changeset slothub:002-create-spaces
CREATE TABLE spaces
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id       BIGINT                   NOT NULL REFERENCES venues (id),
    name           VARCHAR(255)             NOT NULL,
    type           VARCHAR(32)              NOT NULL,
    capacity       INTEGER                  NOT NULL,
    price_per_hour NUMERIC(10, 2)           NOT NULL,
    active         BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
--rollback DROP TABLE spaces;
