--liquibase formatted sql

--changeset p.smirnov:003-create-bookings
CREATE TABLE bookings
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id       BIGINT                   NOT NULL REFERENCES spaces (id),
    customer_name  VARCHAR(255)             NOT NULL,
    customer_email VARCHAR(255)             NOT NULL,
    starts_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    status         VARCHAR(32)              NOT NULL,
    total_price    NUMERIC(10, 2)           NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
--rollback DROP TABLE bookings;
